version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build: .
    ports:
      - "3087:3087"
    environment:
      ASPNETCORE_URLS: "http://+:3087"
      ConnectionStrings__DefaultConnection: "Server=db;Database=TodoDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
      Jwt__Key: "super-secret-key-minimum-32-characters-long!"
      Jwt__Issuer: "Todo.Api"
      Jwt__Audience: "Todo.Api"
    depends_on:
      - db